
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "98f0e2f2f658646a5315f9f54ecc6cc64a5fd660",
 "version": "1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
