#!/usr/bin/env Rscript
install.packages('ggplot2', dep = TRUE, repos="http://cran.r-project.org")
install.packages('gplots', dep = TRUE, repos="http://cran.r-project.org")
install.packages("doMC", dep=TRUE, repos="http://cran.r-project.org")
install.packages("caTools", dep=TRUE, repos="http://cran.r-project.org")
install.packages("utils", dep=TRUE, repos="http://cran.r-project.org")
source("http://bioconductor.org/biocLite.R")
biocLite("BSgenome.Mmusculus.UCSC.mm10", suppressUpdates=TRUE)
biocLite("BSgenome.Mmusculus.UCSC.mm9", suppressUpdates=TRUE)
biocLite("BSgenome.Hsapiens.UCSC.hg19", suppressUpdates=TRUE)
biocLite("BSgenome.Hsapiens.UCSC.hg38", suppressUpdates=TRUE)
biocLite("BSgenome.Scerevisiae.UCSC.sacCer3", suppressUpdates=TRUE)
biocLite("ChIPpeakAnno", suppressUpdates=TRUE)
biocLite("topGO", suppressUpdates=TRUE)
biocLite("edgeR", suppressUpdates=TRUE)
biocLite("Rgraphviz", suppressUpdates=TRUE)
biocLite("Rsamtools", suppressUpdates=TRUE)
biocLite("ShortRead", suppressUpdates=TRUE)
